export const alerts = [
  {
    id: 'cancelled-1',
    type: 'danger',
    title: 'Show Cancelled — Cinepax City Auditorium',
    message:
      'The 7:00 PM showing of Sinners on Thursday has been cancelled due to a technical issue. Alternative shows available at 9:30 PM and Ocean Mall.',
  },
  {
    id: 'almost-full',
    type: 'warning',
    title: 'Almost Full — Nueplex DHA, Screen 2',
    message:
      'The Friday 8:15 PM showing of Mission: Impossible has fewer than 20 seats remaining. Book now to secure your spot.',
  },
  {
    id: 'new-show',
    type: 'info',
    title: 'New Show Added — Atrium Cinemas Saddar',
    message:
      'Due to high demand, a new 11:30 PM late-night showing of Thunderbolts* has been added for the weekend.',
  },
];

export const movies = [
  {
    id: 'sinners',
    title: 'Sinners',
    genre: 'Horror / Thriller',
    tags: ['horror', 'thriller'],
    rating: 8.4,
    duration: '2h 17m',
    age: '18+',
    director: 'Ryan Coogler',
    description:
      'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
    poster: '🎭',
    badge: 'Hot',
    badgeType: 'hot',
    city: 'Karachi',
    featured: true,
    showtimes: [
      { id: 'sinners-1230', time: '12:30 PM', format: '2D', price: 750, venue: 'nueplex', label: 'Available' },
      { id: 'sinners-315', time: '3:15 PM', format: '3D', price: 900, venue: 'nueplex', label: 'Available' },
      { id: 'sinners-700', time: '7:00 PM', format: '2D', price: 750, venue: 'nueplex', label: '18 left' },
      { id: 'sinners-945', time: '9:45 PM', format: 'IMAX', price: 1200, venue: 'nueplex', soldOut: true },
    ],
  },
  {
    id: 'mission',
    title: 'Mission: Impossible – The Final Reckoning',
    genre: 'Action / Adventure',
    tags: ['action'],
    rating: 7.9,
    duration: '2h 49m',
    age: 'PG-13',
    director: 'Christopher McQuarrie',
    description:
      'The impossible mission continues as Ethan Hunt leads his team through a global conspiracy and relentless new enemies.',
    poster: '🕵️',
    badge: 'Now Showing',
    badgeType: 'now',
    city: 'Karachi',
    featured: true,
    showtimes: [
      { id: 'mission-100', time: '1:00 PM', format: '2D', price: 750, venue: 'nueplex', label: 'Available' },
      { id: 'mission-430', time: '4:30 PM', format: '3D', price: 900, venue: 'nueplex', label: 'Available' },
      { id: 'mission-815', time: '8:15 PM', format: '2D', price: 750, venue: 'nueplex', label: 'Limited' },
    ],
  },
  {
    id: 'thunderbolts',
    title: 'Thunderbolts*',
    genre: 'Action / Sci-Fi',
    tags: ['action', 'sci-fi'],
    rating: 7.2,
    duration: '2h 7m',
    age: 'PG-13',
    director: 'Javier Grillo-Marxuach',
    description:
      'A team of unlikely heroes is assembled to save the world from a mysterious new threat in the skies above.',
    poster: '⚡',
    badge: 'Now Showing',
    badgeType: 'now',
    city: 'Karachi',
    featured: false,
    showtimes: [
      { id: 'thunderbolts-200', time: '2:00 PM', format: '4DX', price: 1100, venue: 'atrium', label: 'Available' },
      { id: 'thunderbolts-530', time: '5:30 PM', format: '2D', price: 750, venue: 'atrium', label: 'Available' },
      { id: 'thunderbolts-930', time: '9:30 PM', format: '2D', price: 750, venue: 'atrium', label: 'New' },
    ],
  },
  {
    id: 'loveguru',
    title: 'Love Guru',
    genre: 'Comedy / Romance',
    tags: ['comedy', 'local'],
    rating: 8.1,
    duration: '2h 24m',
    age: 'U/A',
    director: 'Humayun Saeed',
    description:
      'A charming local rom-com about second chances, family pressure, and finding love where you least expect it.',
    poster: '💛',
    badge: 'Local Hit',
    badgeType: 'hot',
    city: 'Karachi',
    featured: false,
    showtimes: [
      { id: 'loveguru-200', time: '2:00 PM', format: '2D', price: 750, venue: 'cinepaxOcean', label: 'Available' },
      { id: 'loveguru-600', time: '6:00 PM', format: '2D', price: 750, venue: 'cinepaxOcean', label: 'Available' },
      { id: 'loveguru-1000', time: '10:00 PM', format: '2D', price: 750, venue: 'cinepaxOcean', label: 'Available' },
    ],
  },
  {
    id: 'how-to-train',
    title: 'How to Train Your Dragon',
    genre: 'Animation / Family',
    tags: ['animation', 'family'],
    rating: 7.6,
    duration: '1h 50m',
    age: 'PG',
    director: 'Dean DeBlois',
    description:
      'A magical return to Berk where riders and dragons soar together against a new sky-threatening danger.',
    poster: '🚀',
    badge: 'Now Showing',
    badgeType: 'now',
    city: 'Karachi',
    featured: false,
    showtimes: [
      { id: 'dragon-130', time: '1:30 PM', format: '2D', price: 650, venue: 'capri', label: 'Available' },
      { id: 'dragon-430', time: '4:30 PM', format: '2D', price: 650, venue: 'capri', label: 'Available' },
      { id: 'dragon-730', time: '7:30 PM', format: '2D', price: 650, venue: 'capri', label: 'Available' },
    ],
  },
  {
    id: 'deemak',
    title: 'Deemak',
    genre: 'Drama',
    tags: ['drama', 'local'],
    rating: 7.0,
    duration: '2h 10m',
    age: 'U/A',
    director: 'Faysal Quraishi',
    description:
      'A character-driven drama about the consequences of ambition and the hidden costs of fame.',
    poster: '🎭',
    badge: 'Now Showing',
    badgeType: 'now',
    city: 'Karachi',
    featured: false,
    showtimes: [
      { id: 'deemak-120', time: '1:20 PM', format: '2D', price: 650, venue: 'cinepaxCity', label: 'Available' },
      { id: 'deemak-420', time: '4:20 PM', format: '2D', price: 650, venue: 'cinepaxCity', label: 'Available' },
    ],
  },
  {
    id: 'jang',
    title: 'Jang-e-Junoon',
    genre: 'Action / Drama',
    tags: ['action', 'local'],
    rating: 8.5,
    duration: '2h 25m',
    age: 'U/A',
    director: 'Ayesha Khan',
    description: 'A high-energy Lahore action drama where rival crews collide over a city-wide film premiere.',
    poster: '🔥',
    badge: 'Local',
    badgeType: 'hot',
    city: 'Lahore',
    featured: true,
    showtimes: [
      { id: 'jang-530', time: '5:30 PM', format: '2D', price: 850, venue: 'packages', label: 'Available' },
      { id: 'jang-830', time: '8:30 PM', format: '2D', price: 850, venue: 'packages', label: 'Available' },
      { id: 'jang-1015', time: '10:15 PM', format: '3D', price: 950, venue: 'emporium', label: 'Late show' },
    ],
  },
  {
    id: 'riverfront',
    title: 'Riverfront Nights',
    genre: 'Romance / Drama',
    tags: ['drama', 'local'],
    rating: 7.9,
    duration: '2h 5m',
    age: 'U/A',
    director: 'Sahir Ali',
    description: 'A warm local story about two strangers whose lives intersect along Lahore’s riverfront.',
    poster: '🌙',
    badge: 'Now Showing',
    badgeType: 'now',
    city: 'Lahore',
    featured: false,
    showtimes: [
      { id: 'river-600', time: '6:00 PM', format: '2D', price: 700, venue: 'emporium', label: 'Available' },
      { id: 'river-930', time: '9:30 PM', format: '2D', price: 700, venue: 'packages', label: 'Available' },
    ],
  },
];

export const venues = [
  {
    id: 'nueplex',
    name: 'Nueplex Cinemas',
    city: 'Karachi',
    location: 'The Place, DHA Phase 8',
    rating: 4.8,
    screens: 5,
    seats: 1200,
    tags: ['gold', 'platinum', '4k', '3d'],
    description: "Pakistan's largest cinema complex. 5 screens, 1200 seats, custom Christie Digital Canada 4K projection.",
    featured: true,
    address: 'The Place, Khayaban-e-Shaheen, DHA Phase 8, Karachi',
    phone: '021-3527-0007',
    hours: '10:00 AM – 12:30 AM',
    amenities: ['Gold Class', 'Platinum', '4K Laser', '3D', 'Parking', 'Snack Bar'],
    screensInfo: [
      { name: 'Screen 1', label: 'Platinum', description: '120 seats · Full recliners · Private attendant' },
      { name: 'Screen 2', label: 'Gold Class', description: '180 seats · Recliner seating · Lounge access' },
      { name: 'Screen 3', label: 'Standard 3D', description: '300 seats · Premium sound' },
    ],
  },
  {
    id: 'cinepaxOcean',
    name: 'Cinepax Ocean Mall',
    city: 'Karachi',
    location: 'Ocean Mall, Clifton',
    rating: 4.5,
    screens: 4,
    seats: 800,
    tags: ['gold', 'imax', '3d'],
    description: 'Family-friendly cinema in Clifton’s Ocean Mall. Clean seating, great snack bar, easy parking.',
    featured: true,
    address: 'Ocean Mall, Clifton Block 9, Karachi',
    phone: '021-3455-8848',
    hours: '10:00 AM – 12:00 AM',
    amenities: ['Gold Class', 'IMAX', '3D', 'Food Court'],
    screensInfo: [
      { name: 'Screen 1', label: 'Gold Class', description: 'Premium recliner seating' },
      { name: 'Screen 4', label: 'IMAX', description: 'Giant screen · Dolby Atmos' },
    ],
  },
  {
    id: 'atrium',
    name: 'Atrium Cinemas',
    city: 'Karachi',
    location: 'Atrium Mall, Saddar',
    rating: 4.3,
    screens: 6,
    seats: 1400,
    tags: ['4dx', 'imax', '3d', 'kids'],
    description: 'Central Karachi entertainment hub with IMAX, 4DX and family screens.',
    featured: true,
    address: 'Atrium Mall, Saddar, Karachi',
    phone: '021-3222-5511',
    hours: '10:00 AM – 12:30 AM',
    amenities: ['4DX', 'IMAX', '3D', 'Kids Screen'],
    screensInfo: [
      { name: 'Screen 1', label: '4DX', description: 'Motion seats · Environmental effects' },
      { name: 'Screen 5', label: 'IMAX', description: 'Large screen · Deep sound' },
    ],
  },
  {
    id: 'cinepaxCity',
    name: 'Cinepax City Auditorium',
    city: 'Karachi',
    location: 'M.A. Jinnah Road, City',
    rating: 4.0,
    screens: 3,
    seats: 650,
    tags: ['gold', '3d'],
    description: 'Classic city-centre auditorium with budget-friendly seating and easy access.',
    featured: false,
    address: 'M.A. Jinnah Road, Saddar, Karachi',
    phone: '021-3257-0044',
    hours: '10:00 AM – 11:30 PM',
    amenities: ['Gold Class', '3D'],
    screensInfo: [{ name: 'Screen 2', label: 'Gold Class', description: 'Comfortable tiered seating' }],
  },
  {
    id: 'capri',
    name: 'Capri Cinema',
    city: 'Karachi',
    location: 'M.A. Jinnah Road, Saddar',
    rating: 3.8,
    screens: 2,
    seats: 500,
    tags: ['classic', '3d'],
    description: "Karachi's historic cinema landmark, recently renovated with modern sound.",
    featured: false,
    address: 'M.A. Jinnah Road, Saddar, Karachi',
    phone: '021-3258-1010',
    hours: '10:00 AM – 11:00 PM',
    amenities: ['Classic', '3D'],
    screensInfo: [{ name: 'Screen 1', label: 'Classic', description: 'Cozy historic experience' }],
  },
  {
    id: 'packages',
    name: 'Cinepax Packages Mall',
    city: 'Lahore',
    location: 'Packages Mall, Walton Road',
    rating: 4.7,
    screens: 7,
    seats: 1400,
    tags: ['gold', '4dx', 'imax', '3d'],
    description: 'Lahore flagship with Gold Class, 4DX, and IMAX experiences.',
    featured: true,
    address: 'Packages Mall, Walton Road, Lahore',
    phone: '042-111-222-777',
    hours: '10:00 AM – 12:30 AM',
    amenities: ['Gold Class', '4DX', 'IMAX', '3D'],
    screensInfo: [{ name: 'Screen 1', label: 'IMAX', description: 'Largest screen in Lahore' }],
  },
  {
    id: 'emporium',
    name: 'Cinepax Emporium',
    city: 'Lahore',
    location: 'Emporium Mall, Johar Town',
    rating: 4.6,
    screens: 6,
    seats: 1100,
    tags: ['gold', '3d'],
    description: 'Popular mall multiplex with premium seating options.',
    featured: false,
    address: 'Emporium Mall, Johar Town, Lahore',
    phone: '042-111-333-555',
    hours: '10:00 AM – 12:00 AM',
    amenities: ['Gold Class', '3D', 'Parking'],
    screensInfo: [{ name: 'Screen 2', label: 'Gold Class', description: 'Luxury recliner seating' }],
  },
];

export const upcomingMovies = [
  {
    id: 'batman-2',
    title: 'The Batman: Part II',
    genre: 'Action / Thriller',
    tags: ['all'],
    release: 'October 2026',
    poster: '🦇',
    badge: 'Most Anticipated',
    releaseDate: 'Oct 2026',
    description: 'Robert Pattinson returns as the caped crusader in the highly anticipated sequel.',
  },
  {
    id: '28-years',
    title: '28 Years Later',
    genre: 'Horror',
    tags: ['june'],
    release: 'Jun 12 2026',
    poster: '🧟',
    badge: 'Jun 12',
  },
  {
    id: 'f1',
    title: 'F1 — The Movie',
    genre: 'Sci-Fi / Action',
    tags: ['june'],
    release: 'Jun 20 2026',
    poster: '🤿',
    badge: 'Jun 20',
  },
  {
    id: 'toy-story-5',
    title: 'Toy Story 5',
    genre: 'Animation',
    tags: ['june'],
    release: 'Jun 27 2026',
    poster: '🌿',
    badge: 'Jun 27',
  },
  {
    id: 'doctor-strange-3',
    title: 'Doctor Strange 3',
    genre: 'Action / Fantasy',
    tags: ['july'],
    release: 'Jul 4 2026',
    poster: '🔮',
    badge: 'Jul 4',
  },
  {
    id: 'jurassic-world',
    title: 'Jurassic World: Rebirth',
    genre: 'Action / Thriller',
    tags: ['july'],
    release: 'Jul 17 2026',
    poster: '🌊',
    badge: 'Jul 17',
  },
  {
    id: 'eid-local',
    title: 'Upcoming Eid Release TBA',
    genre: 'Pakistani / Drama',
    tags: ['july', 'local'],
    release: 'Jul 2026',
    poster: '🇵🇰',
    badge: 'Eid Release',
  },
  {
    id: 'avengers-doomsday',
    title: 'Avengers: Doomsday',
    genre: 'Action / Sci-Fi',
    tags: ['august'],
    release: 'Aug 7 2026',
    poster: '⚡',
    badge: 'Aug 7',
  },
  {
    id: 'pakistani-tba',
    title: 'Pakistani Film TBA',
    genre: 'Family / Drama',
    tags: ['august', 'local'],
    release: 'Aug 14 2026',
    poster: '🏆',
    badge: 'Aug 14',
  },
];

export const seatLayout = {
  rows: 8,
  cols: 12,
  premiumRows: [0, 1],
  takenSeats: ['A4', 'A5', 'B2', 'C8', 'D5', 'E6', 'F7', 'G9', 'H10'],
};
